Repository vndevteam/nestjs-turbo, pull requests merged in 2025-05, with the labels that each got.

#139 test(#105): comment service
  apps/realworld-api/src/api/article/comment/comment.service.spec.ts
Labels: size/L

#142 feat(tools/test): fix postman collection deprecated
  tools/test/realworld-api-old.postman_collection.json
  tools/test/realworld-api.postman_collection.json
Labels: size/XXL

#145 feat: upgrade deps
  apps/docs/package.json
  apps/realworld-api/package.json
  apps/realworld-graphql/package.json
  apps/realworldx-api/package.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/eslint-config/package.json
  packages/graphql/package.json
  packages/mysql-typeorm/package.json
  packages/nest-common/package.json
  packages/postgresql-typeorm/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/M

#148 feat: add validator decorators and fix login validation
  apps/realworld-graphql/src/app.module.ts
  apps/realworld-graphql/src/main.ts
  apps/realworld-graphql/src/modules/auth/dto/auth.dto.ts
  apps/realworld-graphql/src/modules/user/model/user.model.ts
  apps/realworld-graphql/src/schema.gql
  packages/api/src/decorators/field.decorators.ts
  packages/graphql/package.json
  packages/graphql/src/decorators/field.decorators.ts
  packages/graphql/src/index.ts
  packages/graphql/src/utils/index.ts
  packages/graphql/src/utils/register-enum.util.ts
  packages/nest-common/package.json
  pnpm-lock.yaml
Labels: size/XL

#149 feat: add exception handlers and update some configs
  apps/realworld-api/src/api/article/article.controller.ts
  apps/realworld-api/src/api/article/comment/comment.controller.ts
  apps/realworld-api/src/api/article/favorite/favorite.controller.ts
  apps/realworld-api/src/api/profile/profile.controller.ts
  apps/realworld-api/src/api/user/user.controller.ts
  apps/realworld-api/src/filters/global-exception.filter.ts
  apps/realworld-graphql/package.json
  apps/realworld-graphql/src/app.module.ts
  apps/realworld-graphql/src/filters/global-gql-exception.filter.ts
  apps/realworld-graphql/src/guards/auth.guard.ts
  apps/realworld-graphql/src/main.ts
  apps/realworld-graphql/src/modules/auth/auth.resolver.ts
  apps/realworld-graphql/src/modules/auth/dto/auth.dto.ts
  apps/realworld-graphql/src/modules/user/user.resolver.ts
  apps/realworld-graphql/src/modules/user/user.service.ts
  apps/realworld-graphql/src/schema.gql
  apps/realworldx-api/src/api/article/article.controller.ts
  apps/realworldx-api/src/api/article/comment/comment.controller.ts
  apps/realworldx-api/src/api/article/favorite/favorite.controller.ts
  apps/realworldx-api/src/api/profile/profile.controller.ts
  apps/realworldx-api/src/api/user/user.controller.ts
  packages/api/src/decorators/current-user.decorator.ts
  packages/api/src/decorators/index.ts
  packages/graphql/src/constants/app.constant.ts
  packages/graphql/src/constants/graphql-error-code.enum.ts
  packages/graphql/src/constants/index.ts
  packages/graphql/src/decorators/current-user.decorator.ts
  packages/graphql/src/decorators/index.ts
  packages/graphql/src/dto/error-detail.dto.ts
  packages/graphql/src/dto/error.dto.ts
  packages/graphql/src/dto/index.ts
  packages/graphql/src/exceptions/index.ts
  packages/graphql/src/exceptions/validation.exception.ts
  packages/graphql/src/index.ts
  packages/graphql/src/utils/exception-handler.util.ts
  packages/graphql/src/utils/index.ts
  packages/nest-common/src/decorators/index.ts
  pnpm-lock.yaml
Labels: size/L

#150 fix: add & update user logic
  apps/realworld-graphql/src/modules/user/dto/user.dto.ts
  apps/realworld-graphql/src/modules/user/model/user.model.ts
  apps/realworld-graphql/src/modules/user/user.resolver.ts
  apps/realworld-graphql/src/modules/user/user.service.ts
  apps/realworld-graphql/src/schema.gql
  apps/realworldx-api/src/filters/global-exception.filter.ts
  packages/graphql/src/decorators/field.decorators.ts
  tools/test/realworld-graphql.postman_collection.json
Labels: size/L

#154 feat(realworld-graphql): add tag list query
  apps/realworld-graphql/src/modules/tag/model/tag.model.ts
  apps/realworld-graphql/src/modules/tag/tag.module.ts
  apps/realworld-graphql/src/modules/tag/tag.resolver.ts
  apps/realworld-graphql/src/modules/tag/tag.service.ts
  apps/realworld-graphql/src/schema.gql
  tools/test/realworld-graphql.postman_collection.json
Labels: size/L

#155 feat(realworld-graphql): add profile operations
  apps/realworld-graphql/src/modules/profile/dto/profile.dto.ts
  apps/realworld-graphql/src/modules/profile/model/profile.model.ts
  apps/realworld-graphql/src/modules/profile/profile.module.ts
  apps/realworld-graphql/src/modules/profile/profile.resolver.ts
  apps/realworld-graphql/src/modules/profile/profile.service.ts
  apps/realworld-graphql/src/schema.gql
  tools/test/realworld-graphql.postman_collection.json
Labels: size/XL

#157 feat: add article by slug query
  .cursorignore
  apps/realworld-api/src/api/article/article.service.ts
  apps/realworld-graphql/package.json
  apps/realworld-graphql/src/modules/article/article.loader.ts
  apps/realworld-graphql/src/modules/article/article.module.ts
  apps/realworld-graphql/src/modules/article/article.resolver.ts
  apps/realworld-graphql/src/modules/article/article.service.ts
  apps/realworld-graphql/src/modules/article/dto/article.dto.ts
  apps/realworld-graphql/src/modules/article/model/article.model.ts
  apps/realworld-graphql/src/modules/profile/model/profile.model.ts
  apps/realworld-graphql/src/schema.gql
  packages/graphql/package.json
  packages/graphql/src/utils/graphql-fields.util.ts
  packages/graphql/src/utils/index.ts
  pnpm-lock.yaml
  tools/test/realworld-graphql.postman_collection.json
Labels: size/XL

#158 feat: add create article query and refactor some queries
  README.md
  apps/realworld-graphql/src/app.controller.spec.ts
  apps/realworld-graphql/src/app.resolver.ts
  apps/realworld-graphql/src/app.service.ts
  apps/realworld-graphql/src/modules/article/article.resolver.ts
  apps/realworld-graphql/src/modules/article/article.service.ts
  apps/realworld-graphql/src/modules/article/dto/article.dto.ts
  apps/realworld-graphql/src/modules/auth/auth.resolver.ts
  apps/realworld-graphql/src/modules/auth/auth.service.ts
  apps/realworld-graphql/src/modules/profile/profile.resolver.ts
  apps/realworld-graphql/src/modules/tag/model/tag.model.ts
  apps/realworld-graphql/src/modules/tag/tag.resolver.ts
  apps/realworld-graphql/src/modules/tag/tag.service.ts
  apps/realworld-graphql/src/modules/user/user.resolver.ts
  apps/realworld-graphql/src/modules/user/user.service.ts
  apps/realworld-graphql/src/schema.gql
  package.json
  tools/test/realworld-graphql.postman_collection.json
Labels: size/L

#159 feat(realworld-graphql): add logic for update article
  apps/realworld-graphql/src/modules/article/article.resolver.ts
  apps/realworld-graphql/src/modules/article/article.service.ts
  apps/realworld-graphql/src/modules/article/dto/article.dto.ts
  apps/realworld-graphql/src/schema.gql
  tools/test/realworld-graphql.postman_collection.json
Labels: size/L

#160 feat(realworld-graphql): add logic delete article
  apps/realworld-graphql/src/generated/i18n.generated.ts
  apps/realworld-graphql/src/modules/article/article.resolver.ts
  apps/realworld-graphql/src/modules/article/article.service.ts
  apps/realworld-graphql/src/schema.gql
  tools/test/realworld-graphql.postman_collection.json
Labels: size/M

#161 feat: upgrade deps
  apps/docs/package.json
  apps/realworld-graphql/src/generated/i18n.generated.ts
  apps/realworldx-api/package.json
  apps/web/package.json
  package.json
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: size/S

#166 feat(realworld-graphql): add favorite feature
  apps/realworld-api/src/api/article/favorite/favorite.service.ts
  apps/realworld-graphql/src/modules/article/article.loader.ts
  apps/realworld-graphql/src/modules/article/article.module.ts
  apps/realworld-graphql/src/modules/article/article.resolver.ts
  apps/realworld-graphql/src/modules/article/article.service.ts
  apps/realworld-graphql/src/modules/article/favorite/favorite.module.ts
  apps/realworld-graphql/src/modules/article/favorite/favorite.resolver.ts
  apps/realworld-graphql/src/modules/article/favorite/favorite.service.ts
  apps/realworld-graphql/src/schema.gql
  tools/test/realworld-graphql.postman_collection.json
Labels: size/XL
