Repository vndevteam/nestjs-turbo, pull requests merged in 2025-04, with the labels that each got.

#109 feat: upgrade some dev deps
  apps/docs/package.json
  apps/realworld-api/package.json
  apps/realworldx-api/package.json
  apps/user-api/package.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/database-typeorm/package.json
  packages/eslint-config/package.json
  packages/mysql-typeorm/package.json
  packages/nest-common/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/M

#112 docs: update README
  README.md
  apps/realworld-api/README.md
  apps/web/README.md
  packages/eslint-config/README.md
Labels: size/XL

#113 feat: remove user-api
  README.md
  apps/user-api/.env.example
  apps/user-api/.gitignore
  apps/user-api/.prettierrc.mjs
  apps/user-api/README.md
  apps/user-api/eslint.config.mjs
  apps/user-api/nest-cli.json
  apps/user-api/package.json
  apps/user-api/src/app.controller.spec.ts
  apps/user-api/src/app.controller.ts
  apps/user-api/src/app.module.ts
  apps/user-api/src/app.service.ts
  apps/user-api/src/config/config.type.ts
  apps/user-api/src/constants/app.constant.ts
  apps/user-api/src/main.ts
  apps/user-api/test/app.e2e-spec.ts
  apps/user-api/test/jest-e2e.json
  apps/user-api/tsconfig.build.json
  apps/user-api/tsconfig.json
  pnpm-lock.yaml
Labels: size/L

#117 feat: upgrade docs
  apps/docs/.gitignore
  apps/docs/app/_meta.js
  apps/docs/app/docs/[[...mdxPath]]/page.jsx
  apps/docs/app/globals.css
  apps/docs/app/layout.tsx
  apps/docs/app/not-found.ts
  apps/docs/app/page.jsx
  apps/docs/content/_meta.js
  apps/docs/content/index.mdx
  apps/docs/mdx-components.ts
  apps/docs/next.config.mjs
  apps/docs/package.json
  apps/docs/pages/_meta.json
  apps/docs/pages/index.mdx
  apps/docs/postcss.config.mjs
  apps/docs/tailwind.config.ts
  apps/docs/theme.config.tsx
  apps/docs/tsconfig.json
  apps/web/package.json
  packages/eslint-config/README.md
  packages/eslint-config/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/L

#119 feat: add cd for docs
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  apps/docs/next.config.mjs
  apps/docs/package.json
  pnpm-lock.yaml
Labels: size/M

#120 fix: cd for docs
  .github/workflows/deploy-docs.yml
Labels: size/XS

#121 feat: config docs for production
  .github/workflows/deploy-docs.yml
  apps/docs/next.config.mjs
Labels: size/XS

#122 chore: merge develop into main
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  README.md
  apps/docs/.gitignore
  apps/docs/app/_meta.js
  apps/docs/app/docs/[[...mdxPath]]/page.jsx
  apps/docs/app/globals.css
  apps/docs/app/layout.tsx
  apps/docs/app/not-found.ts
  apps/docs/app/page.jsx
  apps/docs/content/_meta.js
  apps/docs/content/index.mdx
  apps/docs/mdx-components.ts
  apps/docs/next.config.mjs
  apps/docs/package.json
  apps/docs/pages/_meta.json
  apps/docs/pages/index.mdx
  apps/docs/postcss.config.mjs
  apps/docs/tailwind.config.ts
  apps/docs/theme.config.tsx
  apps/docs/tsconfig.json
  apps/realworld-api/README.md
  apps/realworld-api/package.json
  apps/realworldx-api/package.json
  apps/user-api/.env.example
  apps/user-api/.gitignore
  apps/user-api/.prettierrc.mjs
  apps/user-api/README.md
  apps/user-api/eslint.config.mjs
  apps/user-api/nest-cli.json
  apps/user-api/package.json
  apps/user-api/src/app.controller.spec.ts
  apps/user-api/src/app.controller.ts
  apps/user-api/src/app.module.ts
  apps/user-api/src/app.service.ts
  apps/user-api/src/config/config.type.ts
  apps/user-api/src/constants/app.constant.ts
  apps/user-api/src/main.ts
  apps/user-api/test/app.e2e-spec.ts
  apps/user-api/test/jest-e2e.json
  apps/user-api/tsconfig.build.json
  apps/user-api/tsconfig.json
  apps/web/README.md
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/database-typeorm/package.json
  packages/eslint-config/README.md
  packages/eslint-config/package.json
  packages/mysql-typeorm/package.json
  packages/nest-common/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: size/XXL

#123 feat: add convention docs
  apps/docs/content/_meta.js
  apps/docs/content/style-guides/_meta.js
  apps/docs/content/style-guides/branch-conventions.mdx
  apps/docs/content/style-guides/clean-code-typescript.mdx
  apps/docs/content/style-guides/commit-conventions.mdx
  apps/docs/content/style-guides/naming-cheatsheet.mdx
  apps/docs/content/style-guides/typescript.mdx
Labels: size/XXL

#124 fix: update some api responses by API testing
  .docker/docker-compose.local.yml
  apps/realworld-api/.env.example
  apps/realworld-api/README.md
  apps/realworld-api/src/api/article/article.controller.spec.ts
  apps/realworld-api/src/api/article/article.controller.ts
  apps/realworld-api/src/api/article/article.service.ts
  apps/realworld-api/src/api/article/article.util.ts
  apps/realworld-api/src/api/user/user.service.ts
  apps/realworldx-api/.env.example
  packages/database-typeorm/.env.example
  packages/mysql-typeorm/.env.example
  tools/test/README.md
  tools/test/realworld.postman_collection.json
  tools/test/run-api-tests.sh
Labels: size/XXL

#125 docs: add api test
  apps/docs/content/testing/_meta.js
  apps/docs/content/testing/api-tests.mdx
Labels: size/M

#126 feat: upgrade deps
  apps/docs/package.json
  apps/realworld-api/package.json
  apps/realworldx-api/package.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/database-typeorm/package.json
  packages/eslint-config/package.json
  packages/mysql-typeorm/package.json
  packages/nest-common/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  tools/test/realworld.postman_collection.json
Labels: size/L

#127 feat: upgrade node version to 22 and support >= 20
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  package.json
Labels: size/XS

#129 feat: fix some type and ci
  .github/workflows/ci.yml
  packages/api/src/decorators/validators/is-ms.decorator.ts
Labels: size/S

#128 chore: merge develop into main
  .docker/docker-compose.local.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  apps/docs/content/_meta.js
  apps/docs/content/style-guides/_meta.js
  apps/docs/content/style-guides/branch-conventions.mdx
  apps/docs/content/style-guides/clean-code-typescript.mdx
  apps/docs/content/style-guides/commit-conventions.mdx
  apps/docs/content/style-guides/naming-cheatsheet.mdx
  apps/docs/content/style-guides/typescript.mdx
  apps/docs/content/testing/_meta.js
  apps/docs/content/testing/api-tests.mdx
  apps/docs/package.json
  apps/realworld-api/.env.example
  apps/realworld-api/README.md
  apps/realworld-api/package.json
  apps/realworld-api/src/api/article/article.controller.spec.ts
  apps/realworld-api/src/api/article/article.controller.ts
  apps/realworld-api/src/api/article/article.service.ts
  apps/realworld-api/src/api/article/article.util.ts
  apps/realworld-api/src/api/user/user.service.ts
  apps/realworldx-api/.env.example
  apps/realworldx-api/package.json
  apps/web/package.json
  package.json
  packages/api/package.json
  packages/api/src/decorators/validators/is-ms.decorator.ts
  packages/database-typeorm/.env.example
  packages/database-typeorm/package.json
  packages/eslint-config/package.json
  packages/mysql-typeorm/.env.example
  packages/mysql-typeorm/package.json
  packages/nest-common/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  tools/test/README.md
  tools/test/realworld.postman_collection.json
  tools/test/run-api-tests.sh
Labels: size/XXL

#131 docs: update README.md and add techstack doc
  apps/docs/content/_meta.js
  apps/docs/content/techstack.md
  apps/realworld-api/README.md
  apps/realworldx-api/README.md
Labels: size/L

#134 feat: add realworld-graphql base
  apps/realworld-graphql/.env.example
  apps/realworld-graphql/.gitignore
  apps/realworld-graphql/.prettierrc.mjs
  apps/realworld-graphql/.swcrc
  apps/realworld-graphql/Dockerfile
  apps/realworld-graphql/README.md
  apps/realworld-graphql/eslint.config.mjs
  apps/realworld-graphql/jest.config.json
  apps/realworld-graphql/nest-cli.json
  apps/realworld-graphql/package.json
  apps/realworld-graphql/setup-jest.mjs
  apps/realworld-graphql/src/app.controller.spec.ts
  apps/realworld-graphql/src/app.module.ts
  apps/realworld-graphql/src/app.resolver.ts
  apps/realworld-graphql/src/app.service.ts
  apps/realworld-graphql/src/config/config.type.ts
  apps/realworld-graphql/src/constants/app.constant.ts
  apps/realworld-graphql/src/constants/constraint-errors.ts
  apps/realworld-graphql/src/constants/error-code.constant.ts
  apps/realworld-graphql/src/database/mysql-typeorm-config.service.ts
  apps/realworld-graphql/src/database/typeorm-config.service.ts
  apps/realworld-graphql/src/filters/global-exception.filter.ts
  apps/realworld-graphql/src/generated/i18n.generated.ts
  apps/realworld-graphql/src/guards/auth.guard.ts
  apps/realworld-graphql/src/i18n/en/app.json
  apps/realworld-graphql/src/i18n/vi/app.json
  apps/realworld-graphql/src/main.ts
  apps/realworld-graphql/src/modules/api.module.ts
  apps/realworld-graphql/src/modules/article/article.module.ts
  apps/realworld-graphql/src/modules/article/comment/comment.module.ts
  apps/realworld-graphql/src/modules/article/favorite/favorite.module.ts
  apps/realworld-graphql/src/modules/auth/auth.module.ts
  apps/realworld-graphql/src/modules/auth/auth.service.ts
  apps/realworld-graphql/src/modules/auth/config/auth-config.spec.ts
  apps/realworld-graphql/src/modules/auth/config/auth-config.type.ts
  apps/realworld-graphql/src/modules/auth/config/auth.config.ts
  apps/realworld-graphql/src/modules/auth/types/jwt-payload.type.ts
  apps/realworld-graphql/src/modules/profile/profile.module.ts
  apps/realworld-graphql/src/modules/tag/tag.module.ts
  apps/realworld-graphql/src/modules/user/user.module.ts
  apps/realworld-graphql/src/utils/unit-test.util.ts
  apps/realworld-graphql/test/app.e2e-spec.ts
  apps/realworld-graphql/test/jest-e2e.json
  apps/realworld-graphql/tsconfig.build.json
  apps/realworld-graphql/tsconfig.json
  pnpm-lock.yaml
Labels: size/XXL

#136 feat(realworld-graphql): fix base project
  apps/realworld-graphql/.env.example
  apps/realworld-graphql/src/app.module.ts
  apps/realworld-graphql/src/filters/global-exception.filter.ts
  apps/realworld-graphql/src/main.ts
  apps/realworld-graphql/src/modules/user/dto/user.dto.ts
  apps/realworld-graphql/src/modules/user/model/user.dto.ts
  apps/realworld-graphql/src/modules/user/user.module.ts
  apps/realworld-graphql/src/modules/user/user.resolver.ts
  apps/realworld-graphql/src/modules/user/user.service.ts
  apps/realworld-graphql/src/schema.gql
  packages/nest-common/src/fastify-pino-logger/fastify-pino.util.ts
Labels: size/L
